In [ ]:
import numpy as np
import pandas as pd

In [ ]:
subs=pd.read_csv('/content/subs.csv').squeeze(True)
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [ ]:
movies=pd.read_csv('/content/bollywood.csv',index_col='movie').squeeze()
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [ ]:
vk=pd.read_csv('/content/kohli_ipl.csv',index_col='match_no').squeeze()
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [ ]:
#astype
import sys
sys.getsizeof(vk)

3604

In [ ]:
sys.getsizeof(vk.astype('int16'))

1024

In [ ]:
#between
vk['runs'].between(51, 99).size

215

In [ ]:
# clip
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [ ]:
subs.clip(100,200)

0      100
1      100
2      100
3      100
4      100
      ...
360    200
361    200
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [ ]:
#drop duplicates
temp=pd.Series([1,1,2,2,3,5,5,6,6])
temp

0    1
1    1
2    2
3    2
4    3
5    5
6    5
7    6
8    6
dtype: int64

In [ ]:
temp.drop_duplicates()

0    1
2    2
4    3
5    5
7    6
dtype: int64

In [ ]:
temp.drop_duplicates(keep='last')

1    1
3    2
4    3
6    5
8    6
dtype: int64

In [ ]:
movies.drop_duplicates()

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Sssshhh...                              Tanishaa Mukerji
Rules: Pyaar Ka Superhit Formula                  Tanuja
Right Here Right Now (film)                        Ankit
Talaash: The Hunt Begins...                Rakhee Gulzar
The Pink Mirror                          Edwin Fernandes
Name: lead, Length: 566, dtype: object

In [ ]:
temp.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8     True
9    False
dtype: bool

In [ ]:
vk.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
210    False
211    False
212    False
213    False
214    False
Length: 215, dtype: bool

In [ ]:
temp=pd.Series([1,2,3,np.nan,5,6,np.nan,8,np.nan,10])
temp

0     1.0
1     2.0
2     3.0
3     NaN
4     5.0
5     6.0
6     NaN
7     8.0
8     NaN
9    10.0
dtype: float64

In [ ]:
temp.size

10

In [ ]:
temp.count()

np.int64(7)

In [ ]:
temp.isnull()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7    False
8     True
9    False
dtype: bool

In [ ]:
temp.dropna()

0     1.0
1     2.0
2     3.0
4     5.0
5     6.0
7     8.0
9    10.0
dtype: float64

In [ ]:
temp.fillna(np.mean(temp))

0     1.0
1     2.0
2     3.0
3     5.0
4     5.0
5     6.0
6     5.0
7     8.0
8     5.0
9    10.0
dtype: float64

In [ ]:
vk[vk['runs'].isin([49, 99])]

    match_no  runs
81        82    99
85        86    49

In [ ]:
vk[vk['runs'].isin([49, 99])]

    match_no  runs
81        82    99
85        86    49

In [ ]:
# apply
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [ ]:
movies.apply(lambda x: x.split()[0].upper())

movie
Uri: The Surgical Strike                  VICKY
Battalion 609                             VICKY
The Accidental Prime Minister (film)     ANUPAM
Why Cheat India                          EMRAAN
Evening Shadows                            MONA
                                         ...
Hum Tumhare Hain Sanam                     SHAH
Aankhen (2002 film)                     AMITABH
Saathiya (film)                           VIVEK
Company (film)                             AJAY
Awara Paagal Deewana                     AKSHAY
Name: lead, Length: 1500, dtype: object

In [ ]:
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [ ]:
subs.mean()

np.float64(135.64383561643837)

In [ ]:
subs.apply(lambda x: 'good day' if x> subs.mean() else 'bad day')

0       bad day
1       bad day
2       bad day
3       bad day
4       bad day
         ...
360    good day
361    good day
362    good day
363    good day
364    good day
Name: Subscribers gained, Length: 365, dtype: object

In [ ]:
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [ ]:
# Copy and view
new=vk.head()
new

match_no
1     1
2    23
3    13
4    12
5     1
Name: runs, dtype: int64

In [ ]:
new[1]=100
new

match_no
1    100
2     23
3     13
4     12
5      1
Name: runs, dtype: int64

In [ ]:
vk

match_no
1      100
2       23
3       13
4       12
5        1
      ...
211      0
212     20
213     73
214     25
215      7
Name: runs, Length: 215, dtype: int64

In [ ]:
new=vk.head().copy()
new

match_no
1    100
2     23
3     13
4     12
5      1
Name: runs, dtype: int64

In [ ]:
new[1]=1
new

match_no
1     1
2    23
3    13
4    12
5     1
Name: runs, dtype: int64

In [ ]:
vk

match_no
1      100
2       23
3       13
4       12
5        1
      ...
211      0
212     20
213     73
214     25
215      7
Name: runs, Length: 215, dtype: int64